//if word Database exists in section name then 1st line is connect string, 
//or name of DNS source file

//Databases (DMS & Mass Tag DBs) connection information
[DMS Database]
Provider=sqloledb;Data Source=gigasax;Initial Catalog=DMS5;User ID=DMSReader;Password=dms4fun
[END]

//access to MTS Master database, which lists databases on all known servers
//first row is connection string, second SP to call to retrieve the data
//third name of field with database name, fourth name of field with description, etc.
[MTS Master Database]
Provider=sqloledb;Data Source=pogo;Initial Catalog=MTS_Master;User ID=MTUser;Password=mt4fun
GetAllMassTagDatabases
Name
Description
State
Server Name
[END]

//all organism mass tag databases should have same schema
[Org MT DB Schema]
//table names
FTICR Analysis Description Table=T_FTICR_Analysis_Description
Match Making Table=T_Match_Making_Description
Analysis Type Table=T_MMD_Type_Name
Peptides Table=T_Peptides
Lockers Table=T_Lockers
Mass Tags Table=T_Mass_Tags
FTICR Peaks Table=T_FTICR_Peak_Results

//sql statements
sql_GET_ICR2LS_Analyses_List_New=SELECT Job AS ID, Dataset_Folder + '\' + Results_Folder AS Name FROM T_FTICR_Analysis_Description WHERE (ResultType = 'HMMA_Peak' AND State=1) ORDER BY Dataset_Folder
sql_GET_ICR2LS_Analyses_List_All=SELECT Job AS ID, Dataset_Folder + '\' + Results_Folder AS Name FROM T_FTICR_Analysis_Description WHERE (ResultType = 'HMMA_Peak') ORDER BY Dataset_Folder
sql_GET_ICR2LS_Analyses_List_Search_Name=SELECT Job AS ID, Dataset_Folder + '\' + Results_Folder AS Name FROM dbo.T_FTICR_Analysis_Description WHERE (ResultType = 'HMMA_Peak') AND (Dataset_Folder + '\' + Results_Folder LIKE '%%')
sql_GET_ICR2LS_Analyses_List_Search_Year=
sql_GET_ICR2LS_Analyses_List_Subset=
sql_GET_Subsets_List=SELECT ID, MTSS_Name, MTSS_Description FROM dbo.T_MTSubset
sql_GET_Locker_Types=SELECT LT_ID, LT_Name FROM dbo.T_Lck_Type_Name

//views - The first two views are for DB Schema Version 1, and are in the MTDB; v_Get_Global_Mass_Correction_Factors and v_Get_Internal_Standard_Names are in MTS_Master
v_Get_Global_Mods_S=v_Global_Mod_S
v_Get_Global_Mods_D=v_Global_Mod_D
v_Get_Global_Mass_Correction_Factors=V_DMS_Mass_Correction_Factors
v_Get_Internal_Standard_Names=V_Internal_Standards

//stored procedures (Only lists SP's used by MassTagsAccess.dll, others are stored in VIPERSettings.ini)
sp_GetDBSchemaVersion=GetDBSchemaVersion
[END]

//URL to DMS info pages so that detailed reports could be displayed in browser
[URL-DMS]
URL_Dataset_Details=http://pogo/dev/dataset_detail_report.asp?datasetNum=
URL_Analysis_Details=http://pogo/dev/analysis_detail_report.asp?jobNum=
URL_Experiment_Details=http://pogo/dev/experiment_detail_report.asp?Experiment_Num=
[END]

[Parameters UMC]
UMC type=1
UMC max gaps=2
UMC max gap size=3
UMC max gap percentage in class=85
UMC MMA=12.5
UMC class overlap allowed=0
UMC pairs require overlap=1
[END]


[Parameters Elution Time]
ET Tol=0.05
ET Type=GANET
ET Formula=Slope * ScanNumber + Intercept
Slope=
Intercept=
[END]


[Parameters Match; Standard]
Fit<=0.25
Standard MMA=5
Standard ET=0.05
Standard ET Type=0
Standard UMC=12.5;2;3;80;Intensity
UMC Mass=Median
UMC Abundance=Sum
PEK=PEK
High Abundance Filter=1
[END]

[Parameters Match; N14/N15]
Pairs N14/N15 Use UMC=1
Pairs N14/N15 MMA=25
Pairs N14/N15 ET=0.15
Pairs N14/N15 ET Type=0
Pairs N14/N15 Delta Mono=0.997
Pairs N14/N15 Delta Tol=0.02
Pairs N14/N15 Use N Count=1
[END]

[Parameters Match; ICAT]
Pairs ICAT Use UMC=1
Pairs ICAT MMA=25
Pairs ICAT ET=0.2
Pairs ICAT ET Type=0
Pairs ICAT Delta Mono=442.2249697
Pairs ICAT Delta Avg=442.581451702418
Pairs ICAT Delta Tol=0.02
Pairs ICAT Use MW Limit=1
[END]

[Parameters Match; Lys-C12/C13]
Pairs Lys-C12/C13 Use UMC=1
Pairs Lys-C12/C13 MMA=25
Pairs Lys-C12/C13 ET=0.2
Pairs Lys-C12/C13 ET Type=0
Pairs Lys-C12/C13 Delta Mono=6.02
Pairs Lys-C12/C13 Delta Tol=0.02
Pairs Lys-C12/C13 Use MW Limit=1
[END]

[Parameters Match; PEO]
Pairs PEO N14/N15 Use UMC=1
Pairs PEO N14/N15 MMA=25
Pairs PEO N14/N15 ET=0.15
Pairs PEO N14/N15 ET Type=0
Pairs PEO N14/N15 Delta Mono=0.997
Pairs PEO N14/N15 Delta Tol=0.02
Pairs PEO N14/N15 Use N Count=1
Pairs PEO N14/N15 Use Cys Count=1
[END]

[Parameters Match; PhIAT]
Pairs PhIAT Use UMC=1
Pairs PhIAT MMA=25
Pairs PhIAT ET=0.2
Pairs PhIAT ET Type=0
[END]

[Parameters Match; Alkylation]
Alkylation Mono=57.0215
[END]

[Parameters Lock]
Lock Use UMC=1
Lock Type=
Lock Description=
Lock Calibration Equation=
Lock Min Lockers/Segment=
[END]

[Label ICAT]
ICAT Name=ICAT
ICAT Formula=
ICAT Mono Mass Light=
ICAT Mono Mass Heavy=
[END]

[Label PEO]
PEO Name=PEO
PEO Formula=
PEO Mono Mass Light=
PEO Mono Mass Heavy=
[END]

[Label PhIAT]
PhIAT Name=PhIAT
PhIAT Formula=
PhIAT Mono Mass Light=
PhIAT Mono Mass Heavy=
[END]
